#!/usr/bin/env bash
#
# init.sh — Initialize Deliberate_Agents for a target project
#
# Creates the .deliberate/ state directory in the project's worktrees root,
# generates a project config, and optionally injects CLAUDE.md into worktrees.
#
# Usage: init.sh [options]
#
# Options:
#   --name <name>             Project name (required)
#   --repo <path>             Path to main repo (required)
#   --worktrees <path>        Path to worktrees root (required)
#   --main-branch <branch>    Main branch name (default: main)
#   --dev-branch <branch>     Development branch name (default: dev)
#   --initiatives <path>      Path to initiatives within repo (default: .documentation/initiatives)
#   --test-cmd <command>      Test command (default: bin/rails test)
#   --system-test-cmd <cmd>   System test command (default: bin/rails test:system)
#   --repo-config             Write config to repo root as .deliberate.yaml (instead of .deliberate/config.yaml)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_DIR="$(dirname "$SCRIPT_DIR")"

# --- Defaults -----------------------------------------------------------------

PROJECT_NAME=""
REPO_DIR=""
WORKTREES_DIR=""
MAIN_BRANCH="main"
DEV_BRANCH="dev"
INITIATIVES_PATH=".documentation/initiatives"
TEST_COMMAND="bin/rails test"
SYSTEM_TEST_COMMAND="bin/rails test:system"
REPO_CONFIG="false"

# --- Argument Parsing ---------------------------------------------------------

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)             PROJECT_NAME="$2"; shift 2 ;;
    --repo)             REPO_DIR="$2"; shift 2 ;;
    --worktrees)        WORKTREES_DIR="$2"; shift 2 ;;
    --main-branch)      MAIN_BRANCH="$2"; shift 2 ;;
    --dev-branch)       DEV_BRANCH="$2"; shift 2 ;;
    --initiatives)      INITIATIVES_PATH="$2"; shift 2 ;;
    --test-cmd)         TEST_COMMAND="$2"; shift 2 ;;
    --system-test-cmd)  SYSTEM_TEST_COMMAND="$2"; shift 2 ;;
    --repo-config)      REPO_CONFIG="true"; shift ;;
    -h|--help)
      sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# --- Validation ---------------------------------------------------------------

[[ -n "$PROJECT_NAME" ]]  || { echo "ERROR: --name is required"; exit 1; }
[[ -n "$REPO_DIR" ]]      || { echo "ERROR: --repo is required"; exit 1; }
[[ -n "$WORKTREES_DIR" ]] || { echo "ERROR: --worktrees is required"; exit 1; }

[[ -d "$REPO_DIR" ]]      || { echo "ERROR: Repo directory does not exist: $REPO_DIR"; exit 1; }
[[ -d "$WORKTREES_DIR" ]] || { echo "ERROR: Worktrees directory does not exist: $WORKTREES_DIR"; exit 1; }

DELIBERATE_DIR="${WORKTREES_DIR}/.deliberate"
PROJECT_SLUG="$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')"

# --- Determine Config Location ------------------------------------------------

if [[ "$REPO_CONFIG" == "true" ]]; then
  CONFIG_FILE="${REPO_DIR}/.deliberate.yaml"
else
  CONFIG_FILE="${DELIBERATE_DIR}/config.yaml"
fi

# Check if already initialized
if [[ -d "$DELIBERATE_DIR" ]]; then
  echo "WARNING: .deliberate/ already exists at $DELIBERATE_DIR"
  read -rp "Reinitialize? This will preserve existing state files. [y/N] " confirm
  if [[ "$confirm" != [yY] ]]; then
    echo "Aborted."
    exit 0
  fi
fi

# --- Create State Directory ---------------------------------------------------

echo "Initializing Deliberate_Agents for: $PROJECT_NAME"
echo "  Repo: $REPO_DIR"
echo "  Worktrees: $WORKTREES_DIR"
echo "  State: $DELIBERATE_DIR"
echo ""

mkdir -p "$DELIBERATE_DIR"/{queue,assignments,status,decisions,logs,qa,pids,feedback}

# --- Generate Config ----------------------------------------------------------

cat > "$CONFIG_FILE" <<EOF
# Deliberate_Agents — Project Configuration
#
# Generated by: init.sh
# Date: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Project: $PROJECT_NAME

project:
  name: "$PROJECT_NAME"
  repo: "$REPO_DIR"
  worktrees: "$WORKTREES_DIR"
  main_branch: "$MAIN_BRANCH"
  dev_branch: "$DEV_BRANCH"
  initiatives_path: "$INITIATIVES_PATH"

agents:
  max_concurrent_developers: 3
  poll_interval_seconds: 30
  autonomy: "full"
  permission_mode: "auto"    # "auto" = safe (may hang on unexpected prompts), "unrestricted" = skip all checks

orchestration:
  tmux_session: "deliberate-${PROJECT_SLUG}"
  log_dir: ".deliberate/logs"

testing:
  command: "$TEST_COMMAND"
  system_test_command: "$SYSTEM_TEST_COMMAND"

stack:
  language: "ruby"
  framework: "rails"
  css: "tailwindcss"
  js: "stimulus"
  design_tool: "claude-design"
EOF

echo "Created config: $CONFIG_FILE"

# --- Register with Framework --------------------------------------------------

FRAMEWORK_CONFIG="${FRAMEWORK_DIR}/config.${PROJECT_SLUG}.yaml"
if [[ ! -e "$FRAMEWORK_CONFIG" ]]; then
  ln -sf "$CONFIG_FILE" "$FRAMEWORK_CONFIG"
  echo "Registered: config.${PROJECT_SLUG}.yaml -> $CONFIG_FILE"
elif [[ -L "$FRAMEWORK_CONFIG" ]]; then
  ln -sf "$CONFIG_FILE" "$FRAMEWORK_CONFIG"
  echo "Updated: config.${PROJECT_SLUG}.yaml -> $CONFIG_FILE"
else
  echo "NOTE: ${FRAMEWORK_CONFIG} exists as regular file — not overwriting"
fi

# --- Create .gitignore --------------------------------------------------------

cat > "${DELIBERATE_DIR}/.gitignore" <<'EOF'
# Deliberate_Agents state — do not commit
logs/
status/
*.log
EOF

echo "Created .gitignore"

# --- Deploy Agent Definitions & Skills ----------------------------------------

echo ""
echo "Deploying agent definitions and skills..."

# Deploy agents/ to the worktrees root so agents in any worktree can find them
# Source of truth is agents/ (organized by team), deployed flat to .claude/agents/
TARGET_CLAUDE_DIR="${WORKTREES_DIR}/.claude"
mkdir -p "${TARGET_CLAUDE_DIR}/agents"
if [[ -d "${FRAMEWORK_DIR}/agents" ]]; then
  find "${FRAMEWORK_DIR}/agents" -name "*.md" -type f -exec cp {} "${TARGET_CLAUDE_DIR}/agents/" \;
  echo "  Deployed agent definitions to ${TARGET_CLAUDE_DIR}/agents/"
else
  echo "  WARNING: No agent definitions found at ${FRAMEWORK_DIR}/agents/"
fi

# Deploy skills/ to .claude/skills/ in the worktrees root
mkdir -p "${TARGET_CLAUDE_DIR}/skills"
if [[ -d "${FRAMEWORK_DIR}/skills" ]]; then
  cp -R "${FRAMEWORK_DIR}/skills/"* "${TARGET_CLAUDE_DIR}/skills/" 2>/dev/null || true
  echo "  Deployed skills to ${TARGET_CLAUDE_DIR}/skills/"
else
  echo "  WARNING: No skills found at ${FRAMEWORK_DIR}/skills/"
fi

# Deploy .mcp.json if template exists
if [[ -f "${FRAMEWORK_DIR}/templates/mcp.json.template" ]]; then
  cp "${FRAMEWORK_DIR}/templates/mcp.json.template" "${WORKTREES_DIR}/.mcp.json"
  echo "  Deployed .mcp.json to ${WORKTREES_DIR}/"
fi

# --- Create Standard Initiative Directories -----------------------------------

INITIATIVES_DIR="${REPO_DIR}/${INITIATIVES_PATH}"
echo ""
echo "Setting up initiative lifecycle directories..."
mkdir -p "${INITIATIVES_DIR}"/{backlog,specified,in-progress,shipped,retired}
echo "  Created: backlog/ specified/ in-progress/ shipped/ retired/"

# --- Verify Dependencies -----------------------------------------------------

echo ""
echo "Checking dependencies..."
"${SCRIPT_DIR}/install-deps.sh" --check-only || true

# --- Summary ------------------------------------------------------------------

echo ""
echo "==========================================="
echo "  Deliberate_Agents initialized!"
echo "==========================================="
echo ""
echo "State directory: $DELIBERATE_DIR"
echo "Config file:     $CONFIG_FILE"

# --- Offer Initiative Organization -------------------------------------------

# Check if there are top-level initiatives that could be organized
TOP_LEVEL_COUNT=0
if [[ -d "$INITIATIVES_DIR" ]]; then
  while IFS= read -r entry; do
    basename="$(basename "$entry")"
    case "$basename" in
      backlog|specified|in-progress|shipped|retired|.*|"Initiative Templates") continue ;;
    esac
    [[ -d "$entry" ]] && TOP_LEVEL_COUNT=$((TOP_LEVEL_COUNT + 1))
  done < <(find "$INITIATIVES_DIR" -maxdepth 1 -mindepth 1 2>/dev/null)
fi

if [[ $TOP_LEVEL_COUNT -gt 0 ]]; then
  echo ""
  echo "Found ${TOP_LEVEL_COUNT} initiative(s) that could be organized into lifecycle directories."
  read -rp "Would you like to organize them? (backlog → specified → in-progress → shipped → retired) [Y/n] " run_organize
  if [[ "$run_organize" != [nN] ]]; then
    "${SCRIPT_DIR}/organize-initiatives.sh" "$CONFIG_FILE" --skip-prompt
  else
    echo ""
    echo "Skipped. You can organize later:"
    echo "  ./scripts/organize-initiatives.sh $CONFIG_FILE"
  fi
fi

# --- Offer Onboarding --------------------------------------------------------

echo ""
read -rp "Would you like to onboard? This explores the codebase, docs, and initiatives to build a project brief. [Y/n] " run_onboard
if [[ "$run_onboard" != [nN] ]]; then
  "${SCRIPT_DIR}/onboard.sh" "$CONFIG_FILE" --skip-prompt
else
  echo ""
  echo "Skipped onboarding. You can run it later:"
  echo "  ./scripts/onboard.sh $CONFIG_FILE"
fi

# --- Next Steps ---------------------------------------------------------------

echo ""
echo "Next steps:"
echo "  1. Review the config: $CONFIG_FILE"
echo "  2. Start the orchestrator:"
echo "     cd $FRAMEWORK_DIR"
echo "     ./orchestration/orchestrate.sh $CONFIG_FILE"
echo ""
echo "  3. Add an initiative:"
echo "     Create a one-pager in $REPO_DIR/$INITIATIVES_PATH/"
echo "     Then create a queue file:"
echo "     cat > $DELIBERATE_DIR/queue/my-initiative.yaml <<EOF"
echo '     initiative: "my-initiative"'
echo '     title: "My Initiative"'
echo '     one_pager_path: "path/to/one-pager.md"'
echo '     status: "QUEUED"'
echo "     created_at: \"$(date -u '+%Y-%m-%dT%H:%M:%SZ')\""
echo "     EOF"
echo ""
